//
// auto-generated by op2.py
//

// header
#include "op_lib_cpp.h"

// user kernel files
#include "init_cubature_omp4kernel.cpp"
#include "init_gauss_omp4kernel.cpp"
#include "init_nodes_omp4kernel.cpp"
#include "init_grid_omp4kernel.cpp"
#include "init_edges_omp4kernel.cpp"
#include "div_omp4kernel.cpp"
#include "curl_omp4kernel.cpp"
#include "grad_omp4kernel.cpp"
#include "cub_grad_omp4kernel.cpp"
#include "cub_div_omp4kernel.cpp"
#include "cub_grad_weak_omp4kernel.cpp"
#include "cub_div_weak_omp4kernel.cpp"
#include "inv_J_omp4kernel.cpp"
