//
// auto-generated by op2.py
//

// header
#include "op_lib_cpp.h"

// user kernel files
#include "init_nodes_omp4kernel.cpp"
#include "init_grid_omp4kernel.cpp"
#include "init_edges_omp4kernel.cpp"
