//
// auto-generated by op2.py
//

void init_gauss_omp4_kernel(
  double *data0,
  int dat0size,
  double *data1,
  int dat1size,
  double *data2,
  int dat2size,
  double *data3,
  int dat3size,
  double *data4,
  int dat4size,
  double *data5,
  int dat5size,
  double *data6,
  int dat6size,
  int count,
  int num_teams,
  int nthread){

  #pragma omp target teams num_teams(num_teams) thread_limit(nthread) map(to:data0[0:dat0size],data1[0:dat1size],data2[0:dat2size],data3[0:dat3size],data4[0:dat4size],data5[0:dat5size],data6[0:dat6size])
  #pragma omp distribute parallel for schedule(static,1)
  for ( int n_op=0; n_op<count; n_op++ ){
    //variable mapping
    double *rx = &data0[21*n_op];
    double *sx = &data1[21*n_op];
    double *ry = &data2[21*n_op];
    double *sy = &data3[21*n_op];
    double *nx = &data4[21*n_op];
    double *ny = &data5[21*n_op];
    double *sJ = &data6[21*n_op];

    //inline function
    

    double J[21];
    for(int i = 0; i < 21; i++) {
      J[i] = -sx[i] * ry[i] + rx[i] * sy[i];
    }

    for(int i = 0; i < 21; i++) {
      double rx_n = sy[i] / J[i];
      double sx_n = -ry[i] / J[i];
      double ry_n = -sx[i] / J[i];
      double sy_n = rx[i] / J[i];
      rx[i] = rx_n;
      sx[i] = sx_n;
      ry[i] = ry_n;
      sy[i] = sy_n;
    }


    for(int i = 0; i < 7; i++) {
      nx[i] = -sx[i];
      ny[i] = -sy[i];
    }

    for(int i = 7; i < 14; i++) {
      nx[i] = rx[i] + sx[i];
      ny[i] = ry[i] + sy[i];
    }

    for(int i = 14; i < 21; i++) {
      nx[i] = -rx[i];
      ny[i] = -ry[i];
    }

    for(int i = 0; i < 21; i++) {
      sJ[i] = sqrt(nx[i] * nx[i] + ny[i] * ny[i]);
      nx[i] = nx[i] / sJ[i];
      ny[i] = ny[i] / sJ[i];
      sJ[i] = sJ[i] * J[i];
    }
    //end inline func
  }

}
