//
// auto-generated by op2.py
//

//user function
__device__ void cub_mm_init_gpu( const int *p, const double *matrix, const double *tmp,
                        double *mm) {

  const int dg_np     = DG_CONSTANTS_cuda[(*p - 1) * 5];
  const int dg_cub_np = DG_CONSTANTS_cuda[(*p - 1) * 5 + 2];
  const double *cubV  = &matrix[(*p - 1) * DG_CUB_NP * DG_NP];

  for(int i = 0; i < dg_np; i++) {
    for(int j = 0; j < dg_np; j++) {
      int mmInd = i + j * dg_np;
      mm[mmInd] = 0.0;
      for(int k = 0; k < dg_cub_np; k++) {
        int aInd = i * dg_cub_np + k;
        int bInd = j * dg_cub_np + k;
        mm[mmInd] += cubV[aInd] * tmp[bInd];
      }
    }
  }

}

// CUDA kernel function
__global__ void op_cuda_cub_mm_init(
  const int *__restrict arg0,
  const double *arg1,
  const double *__restrict arg2,
  double *arg3,
  int   set_size ) {


  //process set elements
  for ( int n=threadIdx.x+blockIdx.x*blockDim.x; n<set_size; n+=blockDim.x*gridDim.x ){

    //user-supplied kernel call
    cub_mm_init_gpu(arg0+n*1,
                arg1,
                arg2+n*DG_CUB_NP * DG_NP,
                arg3+n*DG_NP * DG_NP);
  }
}


//host stub function
void op_par_loop_cub_mm_init(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3){

  double*arg1h = (double *)arg1.data;
  int nargs = 4;
  op_arg args[4];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(1);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[1].name      = name;
  OP_kernels[1].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  cub_mm_init");
  }

  int set_size = op_mpi_halo_exchanges_grouped(set, nargs, args, 2);
  if (set_size > 0) {

    //transfer constants to GPU
    int consts_bytes = 0;
    consts_bytes += ROUND_UP(DG_ORDER * DG_CUB_NP * DG_NP*sizeof(double));
    reallocConstArrays(consts_bytes);
    consts_bytes = 0;
    arg1.data   = OP_consts_h + consts_bytes;
    arg1.data_d = OP_consts_d + consts_bytes;
    for ( int d=0; d<DG_ORDER * DG_CUB_NP * DG_NP; d++ ){
      ((double *)arg1.data)[d] = arg1h[d];
    }
    consts_bytes += ROUND_UP(DG_ORDER * DG_CUB_NP * DG_NP*sizeof(double));
    mvConstArraysToDevice(consts_bytes);

    //set CUDA execution parameters
    #ifdef OP_BLOCK_SIZE_1
      int nthread = OP_BLOCK_SIZE_1;
    #else
      int nthread = OP_block_size;
    #endif

    int nblocks = 200;

    op_cuda_cub_mm_init<<<nblocks,nthread>>>(
      (int *) arg0.data_d,
      (double *) arg1.data_d,
      (double *) arg2.data_d,
      (double *) arg3.data_d,
      set->size );
  }
  op_mpi_set_dirtybit_cuda(nargs, args);
  cutilSafeCall(cudaDeviceSynchronize());
  //update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[1].time     += wall_t2 - wall_t1;
  OP_kernels[1].transfer += (float)set->size * arg0.size;
  OP_kernels[1].transfer += (float)set->size * arg2.size;
  OP_kernels[1].transfer += (float)set->size * arg3.size * 2.0f;
}
